### ISSUE TITLE
AssertionError- pywintypes.py

### ISSUE THREAD

**Issue by SandyHer** [IBT-FMI/SAMRI#36]
When I run "preprocessing.py"  i get the following error

...packages\win32\lib\pywintypes.
py", line 117, in __import_pywin32_system_module__
    assert sys.modules[modname] is not old_mod
AssertionError

I try to solve it with the following suggested solutions but nothing worked.
    1)Commenting out two lines in  in win32/lib/pywintypes.py:
                 #assert sys.modules[modname] is old_mod 
                 #assert mod is old_mod
               pass
     2) Updating pypiwin32 or installing different versions

**Comment by SandyHer** [comment]
@TheChymera

**Comment by TheChymera** [comment]
Hey, sadly we neither use nor recommend using Python on Windows. If you manage to get this to work it would be really great if you wrote a guide for it (ideally using SAMRI should not prescribe your operating system), which would also make it into our documentation. For the time being, however, and in order to prioritize your project, I would recommend one of two other approaches:

* Use SAMRI only on the cluster which I have set up for you (please let me know if you have issues with system administration, on Gentoo Linux - unlike on Windows - I should be able to sort out any issue you might come across).
* Install dual-boot Linux on your laptop/desktop. Here you would have the choice between three distributions:
  * Ubuntu, purportedly the "simplest" (everything is handled via a GUI), but the most difficult for managing neuroscientific software
  * Debian, somewhat more involved than Ubuntu, but with easy access to neuroscientific dependencies (directly via NeuroDebian)
  * Gentoo, the more complex choice, but also the one which is best automatable and the one where I can offer you the most help. Software management is even easier than on Debian here, once you have the system set up. Additionally there is a very helpful and active support channel on IRC.

**Comment by SandyHer** [comment]
Ok, thank you very much for your detailed reply @TheChymera 
So now that i am back at vm, I get the  following error.

OSError: [Errno 2] No such file or directory: '/home/chymera/ni_data/ofM.dr'

What should i do?

**Comment by TheChymera** [comment]
@SandyHer 

There were two problems with that:

* The data directory was not yet present on your clusterhost (I have now made it available under `~/ni_data/`).
* My home path (`/home/chymera/`) was still hard-coded in some functions. I have now [made all the home paths relative](https://github.com/IBT-FMI/SAMRI/commit/41a8c12bef0615cf82bb0a43921a3eb055f02cf6), meaning that they should point to everybody's own `~/ni_data` - including yours.

Let me know if any missing data issues persist.

**Comment by TheChymera** [comment]
Please close this issue if it has been solved :)
