### ISSUE TITLE
Multiple errors: missing file and workflow errors

### ISSUE THREAD

**Issue by SandyHer** [IBT-FMI/SAMRI#41]
1)I get this error a lot during the execution of preprocessing.py

    RuntimeError: Command:
     bet 
 /mnt/data/ni_data/ofM.dr/preprocessing/composite_work/_subject_session_5704.ofM_aF/_scan_type_TurboRARE/s_cutoff/6_corrected_maths.nii.gz /mnt/data/ni_data/ofM.dr/preprocessing/composite_won_5704.ofM_aF/_scan_type_TurboRARE/s_BET/6_corrected_maths_brain.nii.gz -f 0.30 -m -R
Standard output:

Standard error:
/usr/bin/fslval: line 87: /usr/share/fsl/bin/fslhd: No such file or directory
/usr/bin/fslval: line 87: /usr/share/fsl/bin/fslhd: No such file or directory
...

2)And a series of recurring errors that resemble the following:

Return code: 0
Interface BET failed to run.

170807-23:27:03,917 workflow INFO:
         ***********************************
170807-23:27:03,917 workflow ERROR:
         could not run node: composite_work.get_f_scan.aI.a1.b11
170807-23:27:03,917 workflow INFO:
         crashfile: /home/nekda/ni_data/ofM.dr/preprocessing/crashdump/crash-20170807-230220-nekda-get_f_scan.aI.a1.b11-e4024f01-4699-4a3b-93c2-6bd16846c56c.pklz
170807-23:27:03,917 workflow ERROR:
         could not run node: composite_work.get_f_scan.aI.a1.b10

How could I pass these bugs and move on?   @TheChymera

**Comment by TheChymera** [comment]
1) This is apparently a bug with our FSL installation. It's looking for `fslhd` under the FSLDIR: `/usr/share/fsl/bin/fslhd` whereas we install it under `/usr/bin/fslhd`. The reason we have not noticed it is that we d not currently use the conditional `bet` (brain extraction tool) parts of our pipeline. Note how all of the BET code is in [conditional statements](https://github.com/IBT-FMI/SAMRI/blob/master/samri/pipelines/preprocessing.py#L194), just make sure to set `template` and `registration` parameters for the `preprocessing()` function to not trigger those cases.

2) Is normal. Due to the fact that nipype does not yet support conditional execution in their workflows, we check for all combinations of scan types and (subject,session) pairs. If you find this problem interesting, you can try to write a function to determine a priori which combinations exist and only start execution for those - it's not a necessary part of your topic, but it is related. The errors are however [by default set to be not fatal](https://github.com/IBT-FMI/SAMRI/blob/master/samri/pipelines/preprocessing.py#L95). So you can also just move on and maybe return to this once the BIDS support is better implemented.

**Comment by TheChymera** [comment]
Additionally:

```
bet /mnt/data/ni_data/ofM.dr/preprocessing/composite_work/_subject_session_5704.ofM_aF/_scan_type_TurboRARE/s_cutoff/6_corrected_maths.nii.gz /mnt/data/ni_data/ofM.dr/preprocessing/composite_won_5704.ofM_aF/_scan_type_TurboRARE/s_BET/6_corrected_maths_brain.nii.gz -f 0.30 -m -R
```

Fails, because there is no `/mnt/data/ni_data/ofM.dr/preprocessing/composite_won_5704.ofM_aF/_scan_type_TurboRARE/s_BET/6_corrected_maths_brain.nii.gz`. I assume it was supposed to be `/mnt/data/ni_data/ofM.dr/preprocessing/composite_work/_subject_session_5704.ofM_aF/_scan_type_TurboRARE/s_BET/6_corrected_maths_brain.nii.gz`, and it got jumbled in the output. I see no other way to how that path may have been produced.

This will now work:
```
bet /mnt/data/ni_data/ofM.dr/preprocessing/composite_work/_subject_session_5704.ofM_aF/_scan_type_TurboRARE/s_cutoff/6_corrected_maths.nii.gz /mnt/data/ni_data/ofM.dr/preprocessing/composite_work/_subject_session_5704.ofM_aF/_scan_type_TurboRARE/s_BET/6_corrected_maths_brain.nii.gz -f 0.30 -m -R
```

However, I still recommend using the processing without invoking bet.
