### ISSUE TITLE
Nipype_display_crash command not found

### ISSUE THREAD

**Issue by SandyHer** [IBT-FMI/SAMRI#46]
I wanted to create a function for the existing combination of scan_types while I was working on preprocessing.py but when I try to display the crash file with nipype_display_crash I get "command not found"
I tried
1)	Use Nipypecli, as I found that was a possible solution. And I got
pkg_resources.DistributionNotFound: The 'click>=6.6.0' distribution was not found and is required by nipype
2)	Log us root to install/update nipype but I get the following message:
Failed to emerge dev-python/click-6.7, Log file:
The following 2 packages have failed to build, install, or execute
	* postinst:
 	*
*  (dev-python/click-6.7:0/0::gentoo, ebuild scheduled for merge), Log file:
cd*   '/var/tmp/portage/dev-python/click-6.7/temp/build.log'
 	*  (sci-libs/nipype-9999:0/0::science, ebuild scheduled for merge)

How could I make it work?
@TheChymera

**Comment by TheChymera** [comment]
Should be fixed now. Please close the issue if it is.

To give you some context, we are developing SAMRI hand-in-hand with upstream changes to [nipype](https://github.com/nipy/nipype/) - which is why we use a live ebuild (you ca tell that it is live by the `9999` suffix in e.g. the output of `eix -e nipype`).

This means that whenever we run `emerge nipype`, the very newest development version is pulled. We cannot, however, re-install live packages it on every single commit (that would be too often) so we do so on a by-need basis. I need to figure out how to better automatize this, but at the moment, if you get any error from nipype please try to just re-emerge it. Sometimes, upstream code which ends up requiring a dependency is added, and an emerge performed before I notice that a new dependency is need - this happens very seldomly, but it's exactly what happened here, and is automatically fixed on the next emerge.

The `nipypecli` issue was, for instance, easily solved by running `emerge nipype`.

I have no idea what issues you encountered, but if you ever run into build issues again you can pastebin the log to make things more expedient. In the present case that would have been done via `wgetpaste /var/tmp/portage/dev-python/click-6.7/temp/build.log`.
